global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s
  scrape_native_histograms: true

scrape_configs:
  - job_name: retsu
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:2424
        labels:
          deployment_environment: local
          process_mode: api

      - targets:
          - host.docker.internal:24247
        labels:
          deployment_environment: local
          process_mode: worker

  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8888

  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200

  - job_name: prometheus
    static_configs:
      - targets:
          - 127.0.0.1:9090

  - job_name: postgres
    static_configs:
      - targets:
          - pg-exporter:9630
        labels:
          deployment_environment: local

  - job_name: containers
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          deployment_environment: local
    metric_relabel_configs:
      - source_labels:
          - container_label_retsu_observability_component
        regex: postgres
        action: keep
