apiVersion: v1
kind: Namespace
metadata:
  name: retsu-perf
  labels:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/part-of: retsu
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
