apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: retsu
data:
  10-pg-stat-statements.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
