apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: retsu-api
  labels:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: retsu
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retsu
      app.kubernetes.io/component: api
