apiVersion: v1
kind: ConfigMap
metadata:
  name: retsu-config
  labels:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/part-of: retsu
data:
  RETSU_ENVIRONMENT: production
  RETSU_HTTP__BIND_ADDRESS: 0.0.0.0
  RETSU_HTTP__PORT: "2424"
  RETSU_LOGGING__FILTER: info
  RETSU_LOGGING__FORMAT: json
  RETSU_TELEMETRY__METRICS__MAX_QUEUES: "10000"
  RETSU_TELEMETRY__TRACES__ENABLED: "false"
  RETSU_TELEMETRY__TRACES__FILTER: info
  RETSU_TELEMETRY__TRACES__ENDPOINT: http://127.0.0.1:4317
  RETSU_TELEMETRY__TRACES__TIMEOUT_SECONDS: "5"
  RETSU_CACHE__IN_MEMORY__ENABLED: "true"
  RETSU_CACHE__IN_MEMORY__REGIONS__QUEUE_NAMES__MAX_ENTRIES: "10000"
  RETSU_CACHE__IN_MEMORY__REGIONS__QUEUE_NAMES__MAX_CAPACITY_BYTES: "8388608"
  RETSU_CACHE__DISTRIBUTED__ENABLED: "true"
  RETSU_CACHE__DISTRIBUTED__URL: redis://dragonfly:6379
  RETSU_CACHE__DISTRIBUTED__CONNECTION_TIMEOUT_MILLISECONDS: "500"
  RETSU_CACHE__DISTRIBUTED__COMMAND_TIMEOUT_MILLISECONDS: "20"
  RETSU_DATABASE__MAX_CONNECTIONS: "10"
  RETSU_DATABASE__ACQUIRE_TIMEOUT_SECONDS: "5"
  RETSU_WORKER__SHUTDOWN_TIMEOUT_SECONDS: "30"
  RETSU_WORKER__MANAGEMENT__BIND_ADDRESS: 0.0.0.0
  RETSU_WORKER__MANAGEMENT__PORT: "24247"
