apiVersion: v1
kind: Service
metadata:
  name: retsu-expired-message-cleaner
  labels:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/component: expired-message-cleaner
    app.kubernetes.io/part-of: retsu
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/component: expired-message-cleaner
  ports:
    - name: management
      port: 24247
      targetPort: management
      protocol: TCP
