apiVersion: v1
kind: Service
metadata:
  name: retsu-state-metrics-collector
  labels:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/component: state-metrics-collector
    app.kubernetes.io/part-of: retsu
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: retsu
    app.kubernetes.io/component: state-metrics-collector
  ports:
    - name: management
      port: 24247
      targetPort: management
      protocol: TCP
