environment: local

http:
  bind_address: 127.0.0.1
  port: 2424

logging:
  filter: info
  format: pretty

telemetry:
  traces:
    enabled: false
    filter: info
    endpoint: http://127.0.0.1:24241
    timeout_seconds: 5

database:
  url: postgres://retsu:retsu_local@127.0.0.1:24240/retsu
  max_connections: 10
  acquire_timeout_seconds: 5

worker:
  shutdown_timeout_seconds: 30
  management:
    bind_address: 127.0.0.1
    port: 24247
