environment: local

http:
  bind_address: 127.0.0.1
  port: 2424

logging:
  filter: info
  format: pretty

telemetry:
  metrics:
    max_queues: 10000
  traces:
    enabled: false
    filter: info
    endpoint: http://127.0.0.1:24241
    timeout_seconds: 5

cache:
  in_memory:
    enabled: true
    regions:
      queue_names:
        max_entries: 10000
        max_capacity_bytes: 8388608 # 8MB
  distributed:
    enabled: true
    url: redis://127.0.0.1:24251
    connection_timeout_milliseconds: 50
    command_timeout_milliseconds: 20

database:
  url: postgres://retsu:retsu_local@127.0.0.1:24240/retsu
  max_connections: 10
  acquire_timeout_seconds: 5

worker:
  shutdown_timeout_seconds: 30
  management:
    bind_address: 127.0.0.1
    port: 24247
